import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../../theme/theme.dart';
import '../../../models/models.dart';
import '../../../repositories/mock_repository.dart';
import '../../../widgets/widgets.dart';

class ReportsScreen extends StatefulWidget {
  const ReportsScreen({super.key});
  @override
  State<ReportsScreen> createState() => _ReportsScreenState();
}

class _ReportsScreenState extends State<ReportsScreen> {
  List<PatientReport> _reports = [];
  bool _isLoading = true;

  @override
  void initState() { super.initState(); _load(); }

  Future<void> _load() async {
    setState(() => _isLoading = true);
    final r = await MockRepo.getReports();
    if (mounted) setState(() { _reports = r; _isLoading = false; });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: RefreshIndicator(
        color: AppColors.primary,
        onRefresh: _load,
        child: CustomScrollView(
          physics: const AlwaysScrollableScrollPhysics(parent: BouncingScrollPhysics()),
          slivers: [
            SliverAppBar(
              floating: true, snap: true,
              backgroundColor: AppColors.surface,
              surfaceTintColor: Colors.transparent,
              title: Text('My Reports', style: AppTypography.h2),
            ),
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(20, 8, 20, 4),
                child: Text('Reports generated by your care team', style: AppTypography.bodySmall),
              ),
            ),
            _isLoading
                ? SliverToBoxAdapter(child: _skeleton())
                : SliverPadding(
                    padding: const EdgeInsets.all(20),
                    sliver: SliverList.separated(
                      itemCount: _reports.length,
                      separatorBuilder: (_, __) => const SizedBox(height: 12),
                      itemBuilder: (_, i) => _ReportCard(report: _reports[i]),
                    ),
                  ),
            const SliverToBoxAdapter(child: SizedBox(height: 100)),
          ],
        ),
      ),
    );
  }

  Widget _skeleton() => Padding(
    padding: const EdgeInsets.all(20),
    child: Column(children: List.generate(4, (_) => Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Container(height: 140, decoration: BoxDecoration(color: AppColors.inputBg, borderRadius: BorderRadius.circular(20))),
    ))),
  );
}

class _ReportCard extends StatelessWidget {
  final PatientReport report;
  const _ReportCard({required this.report});

  Color get _statusColor {
    switch (report.status) {
      case HealthStatus.normal: return AppColors.green;
      case HealthStatus.warning: return AppColors.amber;
      case HealthStatus.danger: return AppColors.red;
    }
  }

  @override
  Widget build(BuildContext context) {
    final months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    final dateStr = '${months[report.date.month - 1]} ${report.date.day}, ${report.date.year}';
    return AnimatedPressCard(
      onTap: () => HapticFeedback.lightImpact(),
      decoration: AppDecorations.card(),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  width: 44, height: 44,
                  decoration: BoxDecoration(color: _statusColor.withOpacity(0.1), borderRadius: BorderRadius.circular(12)),
                  alignment: Alignment.center,
                  child: Icon(Icons.description_rounded, color: _statusColor, size: 22),
                ),
                const SizedBox(width: 12),
                Expanded(child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(report.title, style: AppTypography.h4.copyWith(fontSize: 15)),
                    const SizedBox(height: 2),
                    Text(report.doctorName, style: AppTypography.bodySmall),
                  ],
                )),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: _statusColor.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(report.status.label, style: AppTypography.labelSmall.copyWith(color: _statusColor, fontWeight: FontWeight.w700)),
                ),
              ],
            ),
            if (report.summary != null) ...[
              const SizedBox(height: 10),
              Text(report.summary!, style: AppTypography.bodySmall, maxLines: 2, overflow: TextOverflow.ellipsis),
            ],
            const SizedBox(height: 10),
            Row(
              children: [
                Icon(Icons.calendar_today_rounded, size: 12, color: AppColors.textTertiary),
                const SizedBox(width: 4),
                Text(dateStr, style: AppTypography.labelSmall),
                const SizedBox(width: 10),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(color: AppColors.blueLight, borderRadius: BorderRadius.circular(8)),
                  child: Text(report.type, style: AppTypography.labelSmall.copyWith(color: AppColors.blue, fontSize: 10)),
                ),
                const Spacer(),
                _SmallAction(icon: Icons.monitor_heart_rounded, label: 'ECG', onTap: () {}),
                const SizedBox(width: 6),
                _SmallAction(icon: Icons.download_rounded, label: 'PDF', onTap: () {}),
                const SizedBox(width: 6),
                _SmallAction(icon: Icons.share_rounded, label: 'Share', onTap: () {}),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _SmallAction extends StatelessWidget {
  final IconData icon; final String label; final VoidCallback onTap;
  const _SmallAction({required this.icon, required this.label, required this.onTap});
  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () { HapticFeedback.lightImpact(); onTap(); },
      borderRadius: BorderRadius.circular(8),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
        decoration: BoxDecoration(
          color: AppColors.primary.withOpacity(0.08),
          borderRadius: BorderRadius.circular(8),
          border: Border.all(color: AppColors.primary.withOpacity(0.15)),
        ),
        child: Row(mainAxisSize: MainAxisSize.min, children: [
          Icon(icon, size: 12, color: AppColors.primary),
          const SizedBox(width: 3),
          Text(label, style: AppTypography.labelSmall.copyWith(color: AppColors.primary, fontWeight: FontWeight.w600, fontSize: 10)),
        ]),
      ),
    );
  }
}
